services:
    _defaults:
        autoconfigure: true

    terminal42_insert_tags.migration.guests:
        class: Terminal42\InsertTagsBundle\Migration\GuestsMigration
        arguments:
            - "@database_connection"
            - "@contao.framework"

    terminal42_insert_tags.migration.duplicate_records:
        class: Terminal42\InsertTagsBundle\Migration\DuplicateRecordsMigration
        arguments:
            - "@database_connection"
            - "@contao.framework"
